source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "rails", "~> 7.0.4"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false

gem "rack-cors"
gem "kaminari"
gem "carrierwave"
gem "carrierwave-aws"
gem "rmagick"
gem "pundit"
gem "sidekiq"
gem "sidekiq-cron"
gem "useragent"
gem "httparty"
gem "bcrypt"
gem "api_guard"
gem "responders"


gem "dotenv-rails", :groups => [:development, :test, :production]

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "byebug"
end

